# This is the config file of the demo instance that is deployed on https://nellygateway.azurewebsites.net

hostUri: https://nellygateway.azurewebsites.net
logoutRedirectUri: https://nellygateway.azurewebsites.net
nellyApiKey: env:NELLY_API_KEY

routes:
  default:
    type: webapplication
    path: /**
    url: https://nellydemoapp.azurewebsites.net
    allowAnonymous: yes
  authenticated:
    type: webapplication
    path: /secure/**
    url: https://nellydemoapp.azurewebsites.net
    allowAnonymous: no

authProviders:
  google:
    authEndpoint: https://accounts.google.com/o/oauth2/auth
    tokenEndpoint: https://oauth2.googleapis.com/token
    clientId: 372143946338-48et57uhmcumku7am3ocvva0idc7u0td.apps.googleusercontent.com
    clientSecret: env:GOOGLE_CLIENT_SECRET
    sessionDuration: 300
    redirectSuccess: https://nellygateway.azurewebsites.net

securityProfiles:
    webapplication:
      headers:
        Server: <<remove>>
        X-Powered-By: <<remove>>
        X-XSS-Protection: 1;mode=block;
        X-Frame-Options: SAMEORIGIN
        X-Content-Type-Options: nosniff
        Referrer-Policy: strict-origin-when-cross-origin
        Content-Security-Policy: upgrade-insecure-requests;base-uri 'self';object-src 'self'
        Permissions-Policy: geolocation=(),notifications=(),push=(),microphone=(),camera=(),speaker=(),vibrate=(),fullscreen=(),payment=(),usb=(),magnetometer=(),gyroscope=(),accelerometer=()
        Strict-Transport-Security: max-age=31536000; includeSubDomains