hostUri: http://localhost:8080

routes:
  httpbin:
    type: webapplication
    path: /**
    url: https://httpbin.org
    allowAnonymous: yes

  echo:
    type: webapplication
    path: /echo/**
    url: https://nellydemoapp.azurewebsites.net
    allowAnonymous: yes


loginProviders:
  google:
    type: oidc
    with:
      authEndpoint: https://accounts.google.com/o/oauth2/auth
      tokenEndpoint: https://oauth2.googleapis.com/token
      clientId: 372143946338-48et57uhmcumku7am3ocvva0idc7u0td.apps.googleusercontent.com
      clientSecret: env:GOOGLE_CLIENT_SECRET
      scopes: [ "openid", "email" ]

  github:
    type: github
    with:
      authEndpoint: https://github.com/login/oauth/authorize
      tokenEndpoint: https://github.com/login/oauth/access_token
      clientId: 163ad3b08c3829216ba1
      clientSecret: env:GITHUB_CLIENT_SECRET
      scopes: [ "user", "email" ]

  auth0:
    type: oidc
    with:
      authEndpoint: https://dev-b6-eperz.eu.auth0.com/authorize
      tokenEndpoint: https://dev-b6-eperz.eu.auth0.com/oauth/token
      clientId: ShvOJHRoa1dH35Oqq17GNcchZDbEmgcz
      clientSecret: env:AUTH0_CLIENT_SECRET
      scopes: [ "openid", "email" ]
      federatedLogoutUrl: https://dev-b6-eperz.eu.auth0.com/v2/logout?client_id=ShvOJHRoa1dH35Oqq17GNcchZDbEmgcz&returnTo=http%3A%2F%2Flocalhost%3A8080

securityProfiles:
  webapplication:
    responseHeaders:
      Server: <<remove>>
      X-Powered-By: <<remove>>
      X-XSS-Protection: 1;mode=block;
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      Referrer-Policy: strict-origin-when-cross-origin
      Content-Security-Policy: base-uri 'self';object-src 'self'
      Permissions-Policy: geolocation=(),notifications=(),push=(),microphone=(),camera=(),speaker=(),vibrate=(),fullscreen=(),payment=(),usb=(),magnetometer=(),gyroscope=(),accelerometer=()
      Strict-Transport-Security: max-age=31536000; includeSubDomains
    userMapping:
      type: "jwt-mapping"
      settings:
        headerName: "Authorization"
        headerPrefix: "Bearer "
        audience: "<<route-url>>"
        issuer: "<<hostUri>>"
        tokenLifetimeSeconds: 30
        signatureImplementation: "rsa"
        signatureSettings:
        mappings:
          provider: <session.provider>
          email_verified: <mappings.email_verified>
          email: <mappings.email>
          picture: <mappings.picture>
          proxy: "OWASP Application Gateway"

traceProfile:
  forwardIncomingTrace: false
  maxLengthIncomingTrace: 254
  acceptAdditionalTraceInfo: false
  maxLengthAdditionalTraceInfo: 254
  sendTraceResponse: true
  type: w3cTrace

keyManagementProfile:
  keyRotationProfile:
    type: defaultKeyRotation
    useSigningKeyRotation: true
    signingKeyRotationSeconds: 28800
    cleanupFrequencySeconds: 10000
  jwkStoreProfile:
    type: localRsaJwkStore
    implSpecificSettings:
      exampleParameter: "not used"
  keyGeneratorProfile:
    type: rsaKeyGenerator
    keySize: 4096
    implSpecificSettings:
      exampleParameter: "not used"