trustedRedirectHosts: [ ]
downstreamApiKey: env:OAG_API_KEY

sessionBehaviour:
  sessionDuration: 3600
  renewWhenLessThan: 1800
  redirectLoginSuccess: /
  redirectLoginFailure: /
  redirectLogout: /

downstreamAuthentication:
  tokenMapping:
    implementation: "jwt-mapping"
    settings:
      headerName:   "Authorization"
      headerPrefix: "Bearer "
      audience:     "<<route-url>>"
      issuer:       "<<hostUri>>"
      tokenLifetimeSeconds: 30
      signatureImplementation: "stub"
      signatureSettings:
        foo: bar

securityProfiles:

  static:
    allowedMethods: [ "GET", "HEAD", "OPTIONS" ]
    csrfProtection: none
    responseHeaders:
      Server: <<remove>>
      X-Powered-By: <<remove>>
      X-XSS-Protection: 1; mode=block;
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      Referrer-Policy: strict-origin-when-cross-origin
      Content-Security-Policy: upgrade-insecure-requests;base-uri 'self';object-src 'self'
      Permissions-Policy: geolocation=(),notifications=(),push=(),microphone=(),camera=(),speaker=(),vibrate=(),fullscreen=(),payment=(),usb=(),magnetometer=(),gyroscope=(),accelerometer=()
      Strict-Transport-Security: max-age=31536000; includeSubDomains

  webapplication:
    allowedMethods: [ "GET", "PUT", "POST", "PATCH", "DELETE", "OPTIONS", "HEAD" ]
    csrfProtection: samesite-strict-cookie
    responseHeaders:
      Server: <<remove>>
      X-Powered-By: <<remove>>
      X-XSS-Protection: 1; mode=block;
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      Referrer-Policy: strict-origin-when-cross-origin
      Content-Security-Policy: upgrade-insecure-requests;base-uri 'self';object-src 'self'
      Permissions-Policy: geolocation=(),notifications=(),push=(),microphone=(),camera=(),speaker=(),vibrate=(),fullscreen=(),payment=(),usb=(),magnetometer=(),gyroscope=(),accelerometer=()
      Strict-Transport-Security: max-age=31536000; includeSubDomains

  apiforspa:
    allowedMethods: [ "GET", "PUT", "POST", "PATCH", "DELETE", "OPTIONS", "HEAD" ]
    csrfProtection: double-submit-cookie
    responseHeaders:
      Server: <<remove>>
      X-Powered-By: <<remove>>
      X-Content-Type-Options: nosniff
      Referrer-Policy: no-referrer
      Content-Security-Policy: upgrade-insecure-requests; default-src 'none'; base-uri 'self'; frame-ancestors 'none'
      Strict-Transport-Security: max-age=31536000; includeSubDomains

  apiforexternal:
    allowedMethods: [ "GET", "PUT", "POST", "PATCH", "DELETE", "OPTIONS", "HEAD" ]
    csrfProtection: none
    responseHeaders:
      Server: <<remove>>
      X-Powered-By: <<remove>>

  raw-proxy:
    allowedMethods: [ "GET", "PUT", "POST", "PATCH", "DELETE", "OPTIONS", "HEAD" ]
    csrfProtection: none
    responseHeaders:

traceProfile:
  forwardIncomingTrace: false
  maxLengthIncomingTrace: 254
  acceptAdditionalTraceInfo: false
  maxLengthAdditionalTraceInfo: 254
  sendTraceResponse: false
  type: w3cTrace
  traceImplSpecificSettings:
    traceImplSpecificParameter: "not used"
