# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven
      run: mvn -B package --file nellygateway/pom.xml 
    - name: Create Artifact Folder
      run: mkdir nellygateway/target/artifact/ && cp nellygateway/target/nellygateway*.jar nellygateway/target/artifact/nellygateway.jar && cp nellygateway/nelly-config.yaml nellygateway/target/artifact/nelly-config.yaml
    - name: Publish Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
          name: Nelly Binary Release
          path: nellygateway/target/artifact/
