# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI/CD with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven
      run: mvn -B package --file nellygateway/pom.xml 
    - name: Create Artifact Folder
      run: mkdir nellygateway/target/artifact/ && cp nellygateway/target/nellygateway*.jar nellygateway/target/artifact/nellygateway.jar && cp nellygateway/sample-nelly-config.yaml nellygateway/target/artifact/sample-nelly-config.yaml
    - name: Add commit hash to artifact
      run: echo $GITHUB_SHA >> nellygateway/target/artifact/comit-hash.txt
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
          path: nellygateway/target/artifact/

  deploy:
    name: Deploy to Azure App Service
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
    - name: 'Copy config file'
      - run: 'cp nelly-config-azure.yaml artifact/nelly-config-azure.yaml'
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: nellygateway
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'artifact/'
