# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI/CD

on:
  push:
    branches: [ dev ]

jobs:
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      # Docker build
      - name: Docker Build
        run: docker build -t owasp/application-gateway:dev-SNAPSHOT .

      # Dockle Check
      - name: Install Dockle
        run: VERSION=$(curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/') && curl -L -o dockle.tar.gz https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz &&  tar zxvf dockle.tar.gz
      - name: Run Dockle Tests
        run: ./dockle --exit-code 1 owasp/application-gateway:dev-SNAPSHOT
      
      # Docker Push
      - name: Docker Login
        run: docker login --username gianlucafrei --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: docker push owasp/application-gateway:dev-SNAPSHOT