name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    
      #############
      # Preparation
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Get version name
        shell: bash
        run: echo "##[set-output name=version;]$(echo ${GITHUB_REF/refs\/tags\//} | sed -ne 's/[^0-9]*\(\([0-9]\.\)\{0,4\}[0-9]\(-[a-zA-Z]*\)*\).*/\1/p')" 
        id: get_version

      - name: Update maven version
        run: mvn versions:set --file oag/pom.xml -DnewVersion=${{ steps.get_version.outputs.version }} -DgenerateBackupPoms=false

      - name: Add commit hash to artifact
        run: echo $GITHUB_SHA >> oag/commit-hash.txt

      - name: "Compile container tag"
        run: echo "tag=owasp/application-gateway:v${{ steps.get_version.outputs.version }}" >> $GITHUB_ENV

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #############
      # Maven build
      # Compiles, signs and deploys OAG to Maven Central
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          directory: oag
          maven_profiles: gpg-sign
          maven_args: "-DskipTests"
          server_id: ossrh
          gpg_private_key: ${{ secrets.GPG_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.MAVEN_USERNAME }}
          nexus_password: ${{ secrets.MAVEN_TOKEN }}

      #############
      # Docker build
      - name: Docker Build
        run: docker build -t ${{ env.tag }} .

      # Dockle Check
      - name: Install Dockle
        run: VERSION=$(curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/') && curl -L -o dockle.tar.gz https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz &&  tar zxvf dockle.tar.gz
      - name: Run Dockle Tests
        run: ./dockle --exit-code 1 ${{ env.tag }}

      # Post build: extract binary from docker build and publish artifact
      - name: Docker create
        run: docker create --name build ${{ env.tag }}
      
      - name: Create build folder
        run: mkdir build

      - name: Copy binary from container
        run: docker cp "build:/app/" build/ 

      - name: Clean up container
        run: docker rm build

      #############
      # zip Artifacts to release
      - name: Create release zip
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: oag-v${{ steps.get_version.outputs.version }}.zip
          directory: '.'
          path: './build/'
        
      # Publish Artifact to release and build-action
      - name: Upload artifacts and release assets
        uses: nanoufo/action-upload-artifacts-and-release-assets@v2
        with:
          path: oag-v${{ steps.get_version.outputs.version }}.zip
          upload-release-files: true
          release-upload-url: ${{ steps.get_release.outputs.upload_url }}
          retention-days: 5

      # Docker Push
      - name: Docker Login
        run: docker login --username gianlucafrei --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: docker push ${{ env.tag }}

      
