server:
  port: 8080
spring:
  application:
    name: nellygateway

zuul:
  ignoredPatterns: /auth/**, /error
  ***REMOVED***
    upstream:
  ***REMOVED***

ribbon:
  eureka:
    enabled: false

org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: DEBUG
logging:
  level:
    org:
      springframework:
        web: DEBUG