nelly:
  configPath: ${NELLY_CONFIG_PATH:sample-nelly-config.yaml}

server:
  port: 8080
spring:
  application:
    name: nellygateway
  banner:
    location: banner.txt

ribbon:
  eureka:
    enabled: false

org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: INFO
logging:
  level:
    root: WARN
    ch:
      gianlucafrei: INFO

  file:
    path: nelly.log


oag:
  session-blacklist-file: "session-blacklist.db"