server:
  port: 8080
spring:
  application:
    name: nellygateway
  banner:
    location: banner.txt

ribbon:
  eureka:
    enabled: false

org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: DEBUG
logging:
  level:
    org:
      springframework:
        web: DEBUG
  file:
    path: nelly.log