nelly:
  configPath: ${NELLY_CONFIG_PATH:sample-nelly-config.yaml}

server:
  port: 8080
spring:
  application:
    name: nellygateway
  banner:
    location: banner.txt

ribbon:
  eureka:
    enabled: false

org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: INFO
logging:
  level:
    root: WARN
    ch:
      gianlucafrei: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %cyan(%X{oag.CorrId}) [%-22.22thread] %highlight(%-5level) - %msg%n"
    file:    "%d{yyyy-MM-dd HH:mm:ss} %X{oag.CorrId} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: oag.log

oag:
  session-blacklist-file: "session-blacklist.db"
